name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore dependencies
      run: nuget restore SCCMCliCtrWPF/SCCMCliCtrWPF.sln
    
    - name: Build (Release)
      run: msbuild SCCMCliCtrWPF/SCCMCliCtrWPF.sln /p:Configuration=Release
      
    - name: Test
      run: dotnet test SCCMCliCtrWPF/SCCMCliCtrTests/SCCMCliCtrTests.csproj --no-build --verbosity normal

